# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igcloned', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='igcloned.Image'),
        ),
        migrations.AddField(
            model_name='comments',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='igcloned.Profile'),
        ),
    ]
