# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 14:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igcloned', '0002_remove_comments_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comment',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='igcloned.Comments'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likes',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
