# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igcloned', '0005_auto_20181005_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comment',
        ),
    ]
