# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igcloned', '0007_remove_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='igcloned.Profile'),
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='igcloned.Profile'),
        ),
        migrations.AddField(
            model_name='likes',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='igcloned.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
