# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-07 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igcloned', '0013_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='current_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
